<table width="96%" align="center" cellpadding="5" cellspacing="2" class="small">
<tr><td width="10%" align="center" valign="top"><span class="title">Grade</span></td><td align="center"><span class="title">Description</span><div>Appearance. Mechanical Condition.</div></td></tr>
<tr><td colspan="2" style="border-top: 2px solid #444;">&nbsp;</td></tr>
<tr><td><b>Not required</b></td><td style="border-left: 1px solid #ccc;">Grade is not required</td></tr>
<tr><td colspan="2" style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td colspan="2" style="border-bottom: 1px solid #ccc;"><b>Used</b></td></tr>
<tr><td align="center" valign="top">10</td><td style="border-left: 1px solid #ccc;">Looks mint, but no guarantees as to whether it was used. All functions work perfectly, not wear.</td></tr>
<tr><td align="center" valign="top">09</td><td style="border-left: 1px solid #ccc;">Polished; edges sharp; markings sharp; machining marks crisp, plating intact, no corrosion, pitting, chips or scratches. All functions work well, though some wear apparent.</td></tr>
<tr><td align="center" valign="top">08</td><td style="border-left: 1px solid #ccc;">Occasional light scratches; minor, normal plating wear; edges may not be sharp; clean. All functions work well, though complete adjustment may not be possible.</td></tr>
<tr><td align="center" valign="top">07</td><td style="border-left: 1px solid #ccc;">Small chips; some plating wear. Normal use and wear.</td></tr>
<tr><td align="center" valign="top">06</td><td style="border-left: 1px solid #ccc;">Chips; small dents; scratches from normal use. All functions work, but some may be fairly worn.</td></tr>
<tr><td align="center" valign="top">05</td><td style="border-left: 1px solid #ccc;">Larger chips and/or scratches. Functions work, but with some difficulty.</td></tr>
<tr><td align="center" valign="top">04</td><td style="border-left: 1px solid #ccc;">Has significant problem. Functional problems requiring replacement parts to make operable.</td></tr>
<tr><td align="center" valign="top">03</td><td style="border-left: 1px solid #ccc;">Major functional problems, possibly due to missing or broken parts that are not easily replaced.</td></tr>
<tr><td align="center" valign="top">02</td><td style="border-left: 1px solid #ccc;">May be useful for parts. Major problems.</td></tr>
<tr><td align="center" valign="top">01</td><td style="border-left: 1px solid #ccc;">No aesthetic value. No mechanical value.</td></tr>
<tr><td colspan="2">&nbsp;</td></tr>
<tr><td colspan="2" style="border-bottom: 1px solid #ccc;"><b>New</b></td></tr>
<tr><td align="center" valign="top">Mint</td><td style="border-left: 1px solid #ccc;">Original factory condition. Never used.</td></tr>
<tr><td align="center" valign="top">NIB</td><td style="border-left: 1px solid #ccc;">New-In-Box.</td></tr>
<tr><td align="center" valign="top">Sale</td><td style="border-left: 1px solid #ccc;">Sale, Inventory clearance sale.</td></tr>
<tr><td align="center" valign="top">Ref</td><td style="border-left: 1px solid #ccc;">Refurbished, Factory second.</td></tr>
<tr><td align="center" valign="top">Disp</td><td style="border-left: 1px solid #ccc;">Display.</td></tr>
</table>