<table width="96%" align="center" cellpadding="5" cellspacing="2" class="small">
<tr><td width="10%" align="center" valign="top"><span class="title">Оценка</span></td><td align="center"><span class="title">Описание</span><div>Оцениваются: внешний вид и состояние механизмов</div></td></tr>
<tr><td colspan="2" style="border-top: 2px solid #444;">&nbsp;</td></tr>
<tr><td><b>Не требуется</b></td><td style="border-left: 1px solid #ccc;">Указывается в случае, когда оценка состояния не требуется.</td></tr>
<tr><td colspan="2" style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td colspan="2" style="border-bottom: 1px solid #ccc;"><b>Бывший в эксплуатации</b></td></tr>
<tr><td align="center" valign="top">10</td><td style="border-left: 1px solid #ccc;">Выглядит как новый, но нет гарантий, что не пользовались. Всё работает отлично, никаких износов.</td></tr>
<tr><td align="center" valign="top">09</td><td style="border-left: 1px solid #ccc;">Без потёртостей. Все кромки без повреждений. Надписи и гравировки чёткие, металлизации без повреждений, никаких следов коррозии, сколов, царапин. Всё хорошо работает, хотя некоторый износ ощущается.</td></tr>
<tr><td align="center" valign="top">08</td><td style="border-left: 1px solid #ccc;">Немного мелких царапин. Незначительный нормальный износ покрытий. Кромки могут быть нечёткими. Чистая. Всё хорошо работает, хотя идеальная настройка может быть недоступной.</td></tr>
<tr><td align="center" valign="top">07</td><td style="border-left: 1px solid #ccc;">Маленькие сколы. Некоторый износ покрытий. Среднее использование и соответствующий износ.</td></tr>
<tr><td align="center" valign="top">06</td><td style="border-left: 1px solid #ccc;">Сколы, мелкие выбоины. Царапины, типичные для нормальной эксплуатуции. Всё работает, но некоторые механизмы могут быть существенно изношены.</td></tr>
<tr><td align="center" valign="top">05</td><td style="border-left: 1px solid #ccc;">Крупнее сколы и/или царапины. Работает, но с трудностями.</td></tr>
<tr><td align="center" valign="top">04</td><td style="border-left: 1px solid #ccc;">Значительные проблемы. Для восстановления работоспособности требуется замена деталей.</td></tr>
<tr><td align="center" valign="top">03</td><td style="border-left: 1px solid #ccc;">Большие проблемы. Утрачены, изношены или сломаны части, которые трудно (дорого) найти и заменить.</td></tr>
<tr><td align="center" valign="top">02</td><td style="border-left: 1px solid #ccc;">Что-то можно пустить на запчасти. Дешевле выбросить, чем восстанавливать.</td></tr>
<tr><td align="center" valign="top">01</td><td style="border-left: 1px solid #ccc;">Не на что смотреть. Хлам.</td></tr>
<tr><td colspan="2">&nbsp;</td></tr>
<tr><td colspan="2" style="border-bottom: 1px solid #ccc;"><b>Новый</b></td></tr>
<tr><td align="center" valign="top">Mint</td><td style="border-left: 1px solid #ccc;">Состояние "только с завода", не использовалось.</td></tr>
<tr><td align="center" valign="top">NIB</td><td style="border-left: 1px solid #ccc;">New-In-Box - "Новое в коробке" - обычно понимается совсем и никак не использовалось.</td></tr>
<tr><td align="center" valign="top">Sale</td><td style="border-left: 1px solid #ccc;">Распродажи.</td></tr>
<tr><td align="center" valign="top">Ref</td><td style="border-left: 1px solid #ccc;">Refurbished - "Восстановленный" - это изделия, по тем или иным причинам возвращённые на завод, где прошли полное приведение к состоянию новых и работоспособных, с полной изначальной гарантией.</td></tr>
<tr><td align="center" valign="top">Disp</td><td style="border-left: 1px solid #ccc;">Display - значит с витрины. Может означать что угодно, от абсолютно новой рабочей или такой, но без коробки и прочего, - до дефектной.</td></tr>
</table>