<table width="96%" align="center" cellpadding="5" cellspacing="2" class="small">
<tr><td class="title">Help</td></tr>
<tr><td>
<div><a href="#1">How to register on bidover.com?</a></div>
<div><a href="#2">How to change profile?</a></div>
<div><a href="#3">Lot listing</a></div>
<div><a href="#4">Seller's Payments</a></div>
<div><a href="#5">Your lot was bought</a></div>
<div><a href="#6">How to buy?</a></div>
<div><a href="#7">You bought!</a></div>
<div><a href="#8">Buyer's Payments</a></div>
<div><a href="#9">Items search</a></div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle" id="1">How to register on bidover.com?</td></tr>
<tr><td>
<div>A registration on the site bidover.com is free. A new registered user is given a bonus of 10 USD for participating in the auction.</div>
<div>Enter your e-mail address in corresponding field on the registration page and press the &laquo;Register&raquo; button. Note your address is written correctly, if the address is entered with a mistake, you will not get the confirmation for a completion of the registration process.</div>
<div>The letter with a login and a password for an authorization will be sent to the e-mail address you indicated. On the &laquo;Authorization&raquo; page enter the login (your login is your e-mail address) and the password and press &laquo;Sign In&raquo;.</div>
<div>On the cover page of your account click the link &laquo;Activate&raquo; or go to the &laquo;Registration package&raquo; tab and fill in data.</div>
<div>In the telephone field enter your contact phone number with the international access code, for example +1-123-1234567. Pay special attention to the Secret word - you will not be able to change the profile and the password without it.</div>
<div>When filling in the form, please give valid and complete data - otherwise later your access can be blocked.</div>
<div>Learn the Agreement.</div>
<div>The confirmation of the registration means the acceptance of all the points and rules stated in the Agreement about rendering of the services at the auction bidOver, and also on all its integral parts. Mark checkbox on the left of the corresponding note, if you accept the Agreement and you are over 18, and press the &laquo;Save&raquo; button.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle" id="2">How to change profile?</td></tr>
<tr><td>
<div>You can change by your own only the password, user's name, address, passport data, and phone.</div>
<div>To do this go to the &laquo;Registration packet&raquo; section, select what you want to change, enter the secret word, edit data and save changes.</div>
<div>You can change the e-mail address if you write to customer.service@bidover.com with an indication of the reason of change.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle" id="3">Lot listing</td></tr>
<tr><td>
<div>All registered users with a positive balance can list an item at the auction bidOver. To do this, go to «Control panel» and press the «Add lot» tab.</div>
<br>
<div><b>Step 1</b> <i>(place lot's description)</i></div>
<div>On the opened page select an appropriate category for your lot(item), the more suitable category you will select, the higher probability of its search by potential buyers. Then fill in the following fields:</div>
<div><b>&laquo;Lot title&raquo;</b> - in this field you give a short description of the item, for example, cell phone Apple iPhone 3G S.  Use the lot title and the words with the help of which a buyer will easily find the lot(item) by key words.</div>
<div><b>&laquo;Lot description&raquo;</b> - in this field you describe your lot(item), for example, body type - classic,  antenna - built-in, device type - smart phone, etc. (in the item description try to answer all important questions which can interest a Buyer, for example: 
<br>- a new item or used 
<br>- what characteristics/sizes/parameters/blemishes an item has, etc. 
<br>- whether an item has a warranty 
</div>
<div><b>&laquo;Lot state&raquo;</b> - in this block you evaluate the state of your lot(item) from suggested options. We suggest you to use &laquo;State estimation assistant&raquo; for more accurate lot state evaluation.</div>
<div><b>&laquo;Buy now&raquo;</b> - here if necessary you indicate the price you are ready to sell a lot(item) before the auction begins.</div>
<div><b>&laquo;Minimal price&raquo;</b> - here if necessary a minimal price you are ready to sell a lot at the auction is indicated. The installation of this parameter is charged in 1 USD. If the price did not reach the lot minimal settled price during the auction, a Seller has the right to refuse the lot selling without punitive measures.</div>
<div><b>&laquo;Lot location&raquo;</b> - here you describe the place your lot(item) is located. For prohibition of bidding of foreign Buyers you can mark checkbox in front of the note.</div>
<div><b>&laquo;Payment&raquo;</b> - here you indicate methods of payment for a lot:
<br>P - a preferred method - it is possible to select only one variant 
<br>A - an alternative method - it is possible to select several variants
<br>In the field &laquo;Payment instructions&raquo; it is possible to add your note to the methods of payment.
</div>
<div><b>&laquo;Shipping and Handling&raquo;</b> - Here you can indicate your variant(s) of a delivery:</div>
<div><b>&laquo;Free shipping&raquo;</b> - A Seller ships a lot(item) for free. 
<br>There are 4 variants of free delivery connected with the location of the lot(item):
<br>- &laquo;Locally&raquo; - the delivery is free within a community.
<br>- &laquo;Inland&raquo; - the delivery is free within a country. 
<br>- &laquo;WorldWide&raquo; - the delivery is free over the world. 
<br>- &laquo;Other&raquo; - here you enter your variant if it is different from suggested above.
</div>
<div><b>&laquo;At the buyer's expense&raquo;</b> - the lot(item) is delivered by a Seller at the buyer's expense. 
<br>There are 2 variants of paid delivery: 
<br>- &laquo;WorldWide&raquo; - a Buyer pays for the delivery (when buying in other country a Buyer should know whether the lot(item) is imposed with customs payments when importing to your country. 
<br>- &laquo;Other&raquo; - here you enter your variant if it is different from suggested above.
</div>
<div>Variants of delivery can combine as &laquo;Free shipping&raquo; and &laquo;At the buyer's expense&raquo;.</div>
<div>For example, a Free shipping within a community and At the buyer's expense over the world.</div>
<div>Indicate obligatorily the time of the lot handling to the Buyer from the moment of its selling. If you have photos ready for browsing click &laquo;Continue&raquo;, if not - mark checkbox in front of the note &laquo;Skip step 2&raquo;. You can add them later in the lot edit regime.</div>
<br>
<div><b>Step 2</b> <i>(uploading photos)</i></div>
<div><b>&laquo;Photo&raquo;</b> - pressing &laquo;Browse&raquo; button in the opened page you select a necessary file with the image for the lot. An image file should be in JPG format and with the size of no more than 100Kb.</div>
<div>Clicking &laquo;Add photo&raquo;, you upload a photo. For every lot you can upload 4 photos. If you finished uploading photo or uploaded 4 photos, click the link &laquo;Carry through upload&raquo;.</div>
<br>
<div>To view, add, delete a photo or to edit a lot description, on the cover page of your profile in the &laquo;Waiting sales&raquo; tab click on the corresponding lot number.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle" id="4">Seller's Payments</td></tr>
<tr><td>
<div>A seller pays:
<br>- A fixed sum of 1 USD for listing the lot for sale, if the lot price is under 10 USD, auction services are free.  
<br>- A sum of 1 USD for minimal price setting. 
<br>- A penalty of 5 USD in the case of refusal of the lot selling, except for the selling of the lot which rate did not reach the minimal set price. 
</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle" id="5">Your lot was bought</td></tr>
<tr><td>A bought lot will move to the &laquo;Waiting decision&raquo; tab. If you consent to sell the lot for this price, you should approve (give your consent) of the deal within 3(three) days. If you approve of selling, the Buyer's contact information will become accessible and the won lot will move to &laquo;Sold&raquo; tab. If you do not consent to sell the lot, you can refuse the deal. If you do not approve (give your consent) of the deal within 3(three) days, the lot will automatically move to the &laquo;Not sold&raquo; tab from which you can list the lot for sale at the auction again. In a month the lot will move to the &laquo;Archives&raquo; tab where it will be during 3(three) months. After shipping the lot you have an opportunity to leave your comments about the deal with this Buyer.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle" id="6">How to buy?</td></tr>
<tr><td>
<div>All registered and not registered users can view lots at the auction bidOver. To buy the lot you liked, you are to register at the auction bidover.com (see &laquo;How to register&raquo;) where you are given an opportunity to try yourself as a Seller and as a Buyer, later you are to have a positive balance.</div>
<div>Firstly, find (<a href="#9">how to search?</a>) the lots(items) that meet your requests, clicking the link &laquo;Lot #&raquo; you can read the lot description, learn about the auction date, shipping and payment, read the information about the Seller if you need to ask the Seller a question.</div>
<div>What you can do with the lot you liked with a suitable description:</div>
<div>1. Not waiting for the auction buy the lot clicking the &laquo;Buy now for ...&raquo; button, if there is such a button. 
<br>The lot will appear in your &laquo;Waiting confirmation&raquo; tab. 
<br>The letter with the contact information of the Seller should come to your e-mail within 3(three) days, and the letter with the contact information of the Seller should come to the control panel in the &laquo;Postbox&raquo; tab, if the letter did not come, the auction is not completed.
</div>
<div id="wdim">2. You can add the lot to the &laquo;Favorites&raquo; tab or make a preliminary bid (<a href="inf.wdim.jsp?<%=System.currentTimeMillis()%>&alt=3">what does it mean?</a>) and (or) a maximum bid (<a href="inf.wdim.jsp?<%=System.currentTimeMillis()%>&alt=4">what does it mean?</a>) and the lot will automatically be added to this folder. In the &laquo;Favorites&raquo; tab you can view detailed information about the lots(items) selected. If the current rate for the lot(item) remained attractive at the day of auction you can take part in the auction selling. The day before the auction and at the day of the auction you will get the letter-reminder about the auction on the lot(item).</div>
<div>At the auction day on the page with the list of lots and on the page with the lot description the link &laquo;Open sales&raquo; will become active, clicking the link you will open a separate window in which interactive bidding will take place.</div>
<br>
<div>For bidding you need to install VMJ (Java Virtual Machine). You can find free download of the program <a href="http://www.java.com/en/download/index.jsp" target="_blank">here</a>. We recommend installing it in advance.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle" id="7">You bought!</td></tr>
<tr><td>
<div>If you bought a lot(item) at the auction bidover.com at the &laquo;Buy now&raquo; rate or bidding, it will appear in your profile in the &laquo;Waiting confirmation&raquo; tab. The lot seller should approve (give his consent) of this deal within 3(three) days. If approved, the lot will move to the &laquo;Confirmed&raquo; tab, and you will have an access to the Seller's contact information for implementation of the formalities connected with a payment and delivery.</div>
<div>After getting the lot you have an opportunity to leave your comments about the deal with this Seller. In a month the lot will move to the &laquo;Archives&raquo; tab where it will be during 3(three) months. If a Seller did not approve (give his consent) of the deal within 3(tree) days, the deal is considered not completed.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle" id="8">Buyer's Payments</td></tr>
<tr><td>
<div>A buyer pays:
<br>- A fixed sum of 1 USD for the buying of the lot the price of which is over 10 USD, if the lot price is under 10 USD, auction services are free. 
<br>- Penalty for 5 USD refusal to buy a lot.
</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle" id="9">Items search</td></tr>
<tr><td>
<div>For registered and not registered users search is available from the main page. On the main page one can search by a key word\phase and in categories.</div>
<div>Using advanced search you can search:
<br>- by the lot number 
<br>- by the user's ID 
<br>- by the key word if necessary using the category and location filter.
</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
</table>