<table width="96%" align="center" cellpadding="5" cellspacing="2" class="small">
<tr><td class="title">Partner Agreement</td></tr>
<tr><td>
<div>This Partner Agreement describes the terms on which the internet auction bidOver.com will cooperate with its Partners. Please, study them and contact us if you have any questions. We strongly recommend to get acquainted with the regulations stated in the present Partner agreement. The acceptance of the present Partner's Agreement will mean that you agree that bidOver will make use of them while you use this Internet resource.</div>
<br>
<div>The present Agreement enters into force from September 18, 2009.</div>
</td></tr>
<tr><td class="smtitle">The subject matter of the Partner Agreement:</td></tr>
<tr><td>The subject matter of the Partner Agreement is providing the auction bidOver of informational-marketing services of searching and attraction of new bidOver users by a Partner.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Using bidOver</td></tr>
<tr><td>
<div>Herewith you declare that while using our services you will not:</div>
<br>
<div>- break any laws, regulations, third party rights and policies of the auction bidOver;</div>
<div>- use our site, services or tools if you are under 18 and not able to conclude obligatory commercial agreements or your access to our site is halt or denied for any reasons;</div>
<div>- spread or post spam, unsolicited or bulk electronic communications, chain letters («letters of happiness»), or pyramid schemes;</div>
<div>- spread viruses or any other technologies that may harm our site, or the interests, rights or property of our users;</div>
<div>- export or re-export any tools except in compliance with the acting legislation;</div>
<div>- copy, modify and distribute rights or content from the this site, service or tools, copyrights and trademarks; or collect information about users, including email addresses, without their consent;</div>
<div>- take any action that may cause (at our discretion) an excessive or disproportionately large load on our infrastructure;</div>
<div>- interfere or try to interfere into intact operative condition of this site, service or tools or any activity taken (on) with the help of the site, its services or tools;</div>
<div>Herewith we inform you that we are authorized to limit, suspend or terminate our partnership, which can cause legal liabilities, or contravene our policies. We also reserve the right to cancel accounts that have been inactive for a long time, or to modify or terminate the operation of our site, its services or tools.</div>
<div>If the auction bidOver.com considers that the Partners act dishonestly: break the terms of cooperation, try to cheat or cheat, we have a right to consider their actions illegal. Partners that fall under this definition are informed by the auction bidOver.com before disqualification (ineligibility) enters into force. We also reserve the right to suspend an access to our site temporarily, without date or forever, if we suspect abuse, criminal use of our programs or interference in functioning of our software.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Auction Obligations:</td></tr>
<tr><td>
<div>The internet auction bidOver can use third parties for providing certain services available through website only. We do not control the third parties and their services and you agree that the company will not be responsible for your actions.</div>
<div>In compliance with the Partner Agreement the auction bidOver is obliged to:</div>
<div>- keep the privacy in respect of the information received from Partners;</div>
<div>- pay for the Partner's services;</div>
<div>- provide Partners with all necessary information in time.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Partner Obligations:</td></tr>
<tr><td>
<div>The Partner is obliged to:</div>
<div>- attract new users to the auction bidOver using his/her own resources and on his/her own account;</div>
<div>- not to attract new users if it is known for certain that they do not meet the Partner's Agreement or Private Policy of the internet auction bidOver.</div>
<br>
<div>The Partner incurs exclusive liability for the content and the methods of his/her actions. Alongside with that the Partner's actions directed to attracting of new users should be structured and prepared professionaly and properly, should not contradict or break law.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Price of Services and Payment procedure</td></tr>
<tr><td>
<div>The registration on bidOver is free, however we verify you as a Partner followed by enumerated means accrual to your account. The means accrual will be based on our Fee Schedule which can be changed occasionally. Changes to that schedule come in force in 30 days after we announce it by posting the corresponding information on the site of the auction bidOver.com. Unless otherwise stated, all fees are quoted in U.S. Dollars. The minimal sum of payment is 10$. You can choose only those methods of means accrual which are available on the auction bidOver.</div>
<div>The accrual of custom fee to the Partner is made every time his/her Refer (the person registrated to the service by your link, called «refer link») completes the deal as a Buyer or a Seller on the auction bidOver.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Limitation of Liability</td></tr>
<tr><td>The internet auction cannot guarantee steady or secure access to our site, services or tools. Work of our sites, services or tools may be negatively influenced with by numerous factors outside of our control. Accordingly, to the extent legally permitted, we exclude all assumed warranties, terms and conditions. We are not responsible for any loss of money, amicability or reputation, or any special, indirect or circumstantial damages emerging, directly or indirectly, out of your use of or your inability to use our site, services and tools.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Privacy</td></tr>
<tr><td>We do not sell or rent your personal information to third parties for their marketing purposes without your explicit consent. We use your information only as described in our Privacy Policy. We view protection of users' privacy as a very important principle of the rendering of our services. If you are not accordant with the conditions laid down about your information being transferred or used please do not use our services.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Indemnity</td></tr>
<tr><td>You will indemnify and hold us (and all our staff) apart from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of your breach of this Agreement, or your violation of any law or the rights of a third party.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">No Agency</td></tr>
<tr><td>No agency, partnership, joint venture, employee-employer or franchiser-franchisee relationship is destined or created by this Agreement.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Notices</td></tr>
<tr><td>Legal notices will be sent to the e-mail address indicated during the process of registration, unless otherwise stated. Notices are considered delivered in 24 hours after its sending, unless the sending part was informed that the e-mail address is invalid.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Resolution of Disputes</td></tr>
<tr><td>If a dispute arises between you and the internet auction bidOver, our goal is to provide you with a neutral and cost effective means of resolving the dispute quickly. Accordingly, you and bidOver agree that we will resolve any claim or controversy at law or equity that arises out of this Agreement or our services in accordance with one of the subsections below or as we and you otherwise agree in writing. Before resorting to these alternatives, we strongly encourage you to first contact us directly to seek a resolution. We will consider reasonable requests to resolve the dispute through alternative dispute resolution procedures, such as mediation or arbitration, as alternatives to litigation.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">General</td></tr>
<tr><td>
<div>If any provision of this Agreement is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced. We do not guarantee we will take action against all breaches of this Agreement.</div>
<br>
<div>We may amend this Agreement at any time by posting the amended terms on this site. Except as stated elsewhere, all amended terms shall automatically be effective 30 days after they are initially posted.</div>
<br>
<div>This Agreement sets forth the entire understanding and agreement between us with respect to the subject matter hereof.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
</table>