<table width="96%" align="center" cellpadding="5" cellspacing="2" class="small">
<tr><td class="title">Privacy Policy</td></tr>
<tr><td>This policy describes how we use and protect your personal data under the legislation in force. In case of any questions, do not hesitate to contact us immediately.</td></tr>
<tr><td>&nbsp;</td></tr>
<tr><td class="smtitle">Collection of information</td></tr>
<tr><td>
<div>You can surf our site without revealing who you are. As soon as you forward us your information, you are no longer anonymous to us and express your consent for transferring and storage of that information on the servers in the United States.</div>
<br>
<div>We may collect and store the following personal information:</div>
<div>email address, other contact information;</div>
<div>business information regarding your activities on the site (such as bidding, purchasing, selling item and content you post or that is connected to  your account);</div>
<div>shipping, invoicing and other information you provide to purchase or ship an item;</div>
<div>other information from your interaction with our site, services, content and advertising, including computer and connection information, statistics on page views, traffic, ad data, IP address and standard web log information;</div>
<div>additional information we ask you to forward to verify your personality or if we believe you are violating site policies (for example, we may ask you to send us an ID or invoice to verify your address, or to answer additional questions online to help verify your identity or ownership of an item you list);</div>
<div>information from other companies, such as demographic and navigation data.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Marketing</td></tr>
<tr><td>We don't sell or rent your personal information to third parties for their marketing purposes without your explicit consent.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Use</td></tr>
<tr><td>
<div>Our main target in collecting your personal information is to offer you assured, efficient, and customized experience while using our site. You agree that we may use your personal information to:</div>
<div>provide the services and customer support you request;</div>
<div>collect fees, and troubleshoot problems;</div>
<div>avert banned or illegal activities, and enforce our User Agreement;</div>
<div>customize, measure and improve our services, content and advertising;</div>
<div>forward information about our services, new marketing, service updates, and promotional offers based on your communication preferences; and</div>
<div>compare information for accuracy, and verify it with third parties.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Our Disclosure of Your Information</td></tr>
<tr><td>We may reveal personal information to meet the applicable laws and regulations, enforce our policies, respond to claims, or protect anyone's rights, property, or safety.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Information You Share on our site</td></tr>
<tr><td>
<div>Your User ID is displayed throughout BidOver (and so it is available to the public), and is connected to all of your activities on the site. Other people can see your bids, purchases, listed items,  feedback, ratings and comments. Notices sent to other community members about suspicious activity and policy violations on our site refer to User IDs and specific items. So if you associate your name with your User ID, the people to whom you have disclosed your name will be able to authenticate your activities on our site.</div>
<div>If you access our site from a shared computer or a computer in an internet café, certain information about you, such as your User ID, activity or reminders from our site, may also be visible to other individuals who use the computer after you.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Using Information from our site</td></tr>
<tr><td>
<div>bidOver enables you to share personal and financial information to complete the deals. We ask you kindly to reveal your privacy practices and respect the privacy of other users. We cannot assure the privacy or security of your information and therefore we call you up to evaluate the privacy and security policies of your business partner before entering into a transaction and choosing to share your information. To help protect your privacy, we allow only limited access to other users' contact, shipping and financial information to assist in your deal. When users are involved in a deal they may have access to each other's name, User ID, email address and other contact and shipping information. In all cases, you must give other users a chance to remove themselves from your database and a chance to review what information you have collected about them.</div>
<br>
<div>You agree to use user information only for:</div>
<div>bidOver transaction-related purposes that are not unsolicited commercial messages (spam);</div>
<div>using services offered through bidOver (e.g. escrow, insurance, shipping and fraud complaints), or other purposes that a user explicitly chooses.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Cookies</td></tr>
<tr><td>
<div>We use "cookies" (small files placed on your hard drive) on certain of our pages to help analyze our web page statistics; customize our services, content and advertising; measure promotional effectiveness, and promote trust and safety.</div>
<br>
<div>Some  important things you should know about cookies are that:</div>
<div>We offer certain features that are available only through the use of cookies.</div>
<div>We use cookies to help authenticate you and support your signed-in status.</div>
<div>Most cookies are "session cookies", meaning that they are automatically deleted from your hard drive at the end of a session.</div>
<div>You are always free to decline our cookies if your browser permits, although doing so may interfere with your use of some parts of the site or services.</div>
<div>You may come across cookies from third parties on certain pages of the site that we do not control. (For example, if you view a web page created by another user, there may be a cookie placed by that web page.)</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">No Spam, Spyware or Spoofing</td></tr>
<tr><td>We and our users do not stand spam. Make sure to set your bidOver notification preferences so we communicate to you as you prefer. You are not authorized  to add other users, even a user who has purchased an item from you, to your mailing list (email or physical mail) without their explicit consent. To report about spam or spoof emails, please forward the email to spam@bidover.com. You can not use our tools to send spam or otherwise send content that can break our User Agreement. We automatically scan and may manually filter messages to check for spam, viruses, fishing attacks and other malicious activity or illegal or banned content, but we do not permanently store messages sent through these tools. If you send an email to an email address that is not registered in our community, we do not permanently store that email or use that email address for any marketing purpose. We do not rent or sell these email addresses.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Account Protection</td></tr>
<tr><td>Your password is the key to your account. Use unique numbers, letters and special characters, and do not reveal your bidOver password to anyone. If you do share your password or your personal information with others, remember that you are responsible for all actions taken in the name of your account. If you lose control of your password, you may lose control over your personal data and may be subject to legally binding actions taken on your behalf. Therefore, if your password has been compromised for any reason, you should immediately notify bidOver and change your password.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Accessing, Reviewing and Changing Your Personal Information</td></tr>
<tr><td>You can see, review and change most of your personal data by asking bidOver. In general, we will not manually update your personal information because it is very difficult to verify your personality remotely. You must promptly update your personal information if it changes or is inaccurate. Once you make a public posting, you may not be able to change or remove it. Upon your request, we will close your account and remove your personal information from view as soon as reasonably possible, based on your account activity and in accordance with applicable law. We do keep personal information off from closed accounts to comply with law, prevent fraud, collect any fees owed, resolve disputes, troubleshoot problems, assist with any investigations, enforce our User Agreement, and take other actions otherwise allowed by law.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Security</td></tr>
<tr><td>Your information is stored on servers located in the United States. We treat data as an asset that must be protected and use lots of tools (encryption, passwords, etc.) to protect your personal data against unauthorized access and reveal. However, as you probably know, third parties may unlawfully interfere or access transmissions or private communications, and other users may abuse or misuse your personal data that they collect from the site. Therefore, although we work very hard to protect your privacy, we do not promise, and you should not expect, that your personal information or private communications will always remain private.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Third Parties</td></tr>
<tr><td>Except as otherwise explicitly concluded in this Privacy Policy, this document addresses only the use and revealing of information we collect from you. If you reveal your information to others, whether they are bidders, buyers or sellers on our site or other sites throughout the internet, different rules may apply to their use or disclosure of the information you disclose to them. bidOver does not control the privacy policies of third parties, and you are subject to the privacy policies of those third parties where applicable. We ask you kindly to ask questions before you reveal your personal information to others.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">General</td></tr>
<tr><td>Herewith we inform you that reserve the right to amend the present Privacy Policy at any time by introducing the amended conditions on this site. All amended terms automatically take effect in 30 days after they are posted on the site. In addition, we will keep you informed through our Message Center. If your questions are not answered online, you may using the Contact Us form.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
</table>