<br><b>Unregistered users have the possibility:</b>
<br>1. to view lots submitted to sales 
<br>2. to browse categories of the website for general use 
<br>
<br><b>Possibilities of registered user:</b>
<br>1. to submit goods for sales 
<br>2. to make preliminary bids 
<br>3. to make immediate purchases
<br>4. participate in online auctions 
<br>5. form a list of  favorite lots 
<br>6. leave feedbacks
<br>
<br><b>Registration consists of 2 phases:</b>
<br>1st stage - registration and receiving of the password for authentication on the site (entrance to the Control Panel). 
<br>2nd stage - "the signing" (accept) of user agreement and activation your account.