<table width="96%" align="center" cellpadding="5" cellspacing="2" class="small">
<tr><td class="title">User Agreement</td></tr>
<tr><td>
<div>Here are the terms on which bidOver renders its services to its Users. Please, study them and in case you have any questions do not hesitate to contact us. We strongly recommend to get acquainted with the provisions stated in the present User's Agreement and corresponding Privacy Policy. The acceptance of the present User's Agreement will mean that you agree that bidOver will make use of them while you use this Internet resource.</div>
<br>
<div>The present Agreement enters into force from July 31, 2009.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Using bidOver</td></tr>
<tr><td>
<div>Herewith you declare that while using our services you will not:</div>
<br>
<div>put information  or submit information upon the items in irrelevant categories or areas on our site;</div>
<div>break any laws, regulations, third party rights or our policies mentioned below;</div>
<div>use our sites services or tools if you are under 18 and not able to conclude obligatory commercial agreements or your access to our site is halt or denied for any reasons;</div>
<div>fail to effect the payment in due time for the items purchased by you, unless the seller has significantly changed the item's description after you submit a bid, a definite typing error is made, or you cannot  establish as genuine or valid the seller's personality;</div>
<div>fail to deliver items bought from you, unless the buyer fails to fulfill the agreed commitments, or you cannot establish as genuine or valid the buyer's personality;</div>
<div>negotiate the price of any item or  intervene with other users' listings;</div>
<div>outwit or wangle our fee and the invoicing process, or fees imposed by bidOver;</div>
<div>post wrong, inexact, deceiving, defamatory, or libelous content (including personal information);</div>
<div>take any action that may weaken or damage the feedback or ratings systems (such as displaying, importing or exporting this information off of the site or using it for purposes other than  described on bidOver);</div>
<div>transfer your account (including feedback) and User ID to another party without agreement with bidOver;</div>
<div>spread or post spam, unsolicited or bulk electronic communications, chain letters, or pyramid schemes;</div>
<div>distribute viruses or any other technologies that may harm our site, or the interests, rights or property of our users;</div>
<div>export or re-export any tools except in compliance with the acting legislation;</div>
<div>copy, modify or distribute rights or content from the this site, service or tools or  copyrights and trademarks; or</div>
<div>otherwise collect information about users, including email addresses, without their consent.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Abusing bidOver</td></tr>
<tr><td>
<div>The staff of our website is working hard to keep it operate properly and safe. In case of any problems, offensive content and breach of our policy we ask you kindly to report about them immediately.</div>
<br>
<div>Herewith we inform you that we are authorized to limit, suspend or terminate our service and user accounts, prohibit access to our site and its content, services and tools, delay or remove hosted content, and take technical and legal steps to keep users off the site if we think that they are creating problems, possible legal liabilities, or contravene our policies. We also reserve the right to cancel unconfirmed accounts or accounts that have been inactive for a long time, or to modify or terminate the operation of  our site,  its services or tools.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">bidOver Purchase Protection</td></tr>
<tr><td>
<div>Buyers and sellers share the responsibility of concluding lawful and safe business translations moderated by bidOver. We insistently call on buyers and sellers work jointly in order to settle the claims and disputes in amicable mode.</div>
<br>
<div><b>Buyer Obligations:</b></div>
<div>In case bidOver believes that Buyers are not acting honestly, violating the program or a seller, attempting to commit or committing fraud, or trying to unjustly benefit from the program we are authorized to consider them ineligible. Buyers who become ineligible will be notified by bidOver before the ineligibility comes into force.  We reserve the right to temporarily, indefinitely or permanently suspend access to our site if we suspect abuse, tampering, or interference with the proper working of our software.</div>
<br>
<div><b>Seller Obligations:</b></div>
<div>All sellers with an open claim must work in good faith to settle the claim, refund money and/or provide a replacement item, and accept its return.</div>
<br>
<div>Obligations when a buyer opens a claim announcing an item is counterfeit:</div>
<div>Sellers shall work with the buyer in good faith upon the settlement of this situation and provide buyer with appropriate documentation or other assurances convincing the buyer that the item is not faked, if such information is available.</div>
<div>If buyer and seller cannot agree that the item is not counterfeit, buyers are required to send the item back to the seller. Cost of return shipping will be paid by the buyer, unless otherwise agreed upon by the buyer and seller.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Fees and Services</td></tr>
<tr><td>
<div>Joining bidOver is free. We impose fees for using other services, such as listing items. When you list an item or use a service that is not free of charge, you have can review and accept the fees that you will owe visiting our  <a href="">Fees schedule</a>, which we may change occasionally. Changes to that schedule come in force at least fourteen days after we announce it by posting the revised fees on the bidOver site. We may choose to temporarily change the fees for our services for promotional events (for example, free listing days) or new services, and such changes are effective when we announce the temporary promotional event or new service on the sites.</div>
<br>
<div>Unless otherwise stated, all fees are quoted in U.S. Dollars. You are responsible for paying all fees and applicable taxes connected with our site and services in due time and  with a valid payment method.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Content</td></tr>
<tr><td>When you give us content, you grant us a non-exclusive, worldwide, permanent, irrevocable, royalty-free, sublicense able (through multiple tiers) right to exercise the copyright, trademark, publicity, and database rights (but no other rights) you have in the content, in any media known now or in the future.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Limitation of Liability</td></tr>
<tr><td>
<div>bidOver is not liable for other users' content, actions or inactions, items they list or their destruction of allegedly counterfeit items. We are not involved in the actual deals between buyers and sellers. We have no control over and do not guarantee the quality, safety or legality of items advertised, the truth or accuracy of users’ content or listings, the ability of sellers to sell items, the ability of buyers to pay for items, or that a buyer or seller will actually complete a transaction or return an item.</div>
<br>
<div>We do not transfer right of property of items from the seller to the buyer, unless the buyer and the seller agree otherwise. Further, we cannot guarantee steady or secure access to our site, services or tools, and work of our sites, services or tools may be negatively influenced with by numerous factors outside of our control. Accordingly, to the extent legally permitted, we exclude all assumed warranties, terms and conditions. We are not responsible for any loss of money, amicability or reputation, or any special, indirect or circumstantial damages emerging, directly or indirectly, out of your use of or your inability to use our site, services and tools.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Release</td></tr>
<tr><td>If you have a dispute with one or more users, you release us (and all our staff) from claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, arising out of or in any way connected with such disputes.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Access and Interference</td></tr>
<tr><td>
<div>Much of the information on the site is updated on a real-time basis and is owned to us by our users or third parties. You agree that you will not use any robot, spider, scraper or other automated means to access the site for any purpose without our explicit hand written permission.</div>
<br>
<div>Additionally, you express your consent that you will not:</div>
<div>take any action that imposes or may impose (in our sole discretion) an unreasonable or enormously large load on our infrastructure;</div>
<div>copy, reproduce, modify, create derivative works from, distribute, or publicly display any content (except for your information) from the present site without our explicit hand written permission and the appropriate third party, as applicable;</div>
<div>meddle or try to meddle in the proper working of the site, services or tools, or any activities carried out on or with the sites, services or tools; or</div>
<div>other measures we may use to prevent or restrict access to the site.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Privacy</td></tr>
<tr><td>We do not sell or rent your personal information to third parties for their marketing purposes without your explicit consent. We use your information only as described in our Privacy Policy. We view protection of users' privacy as a very important principle of the rendering of our services. You can access and modify the information you submitted and decide not to receive certain communications by signing-in to your account. If you protest to your information being transferred or used in this way please do not use our services.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Indemnity</td></tr>
<tr><td>You will indemnify and hold us (and all our staff) apart from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of your breach of this Agreement, or your violation of any law or the rights of a third party.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">No Agency</td></tr>
<tr><td>No agency, partnership, joint venture, employee-employer or franchiser-franchisee relationship is destined or created by this Agreement.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Notices</td></tr>
<tr><td>Except as explicitly stated otherwise, legal notices shall be sent to the email address you indicated at registration. Notice shall be considered in the course of 24 hours after email is sent, unless the sending party is notified that the email address is invalid.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">Resolution of Disputes</td></tr>
<tr><td>If a dispute arises between you and bidOver, our goal is to provide you with a neutral and cost effective means of resolving the dispute quickly. Accordingly, you and bidOver agree that we will resolve any claim or controversy at law or equity that arises out of this Agreement or our services in accordance with one of the subsections below or as we and you otherwise agree in writing. Before resorting to these alternatives, we strongly encourage you to first contact us directly to seek a resolution. We will consider reasonable requests to resolve the dispute through alternative dispute resolution procedures, such as mediation or arbitration, as alternatives to litigation.</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
<tr><td class="smtitle">General</td></tr>
<tr><td>
<div>If any provision of this Agreement is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced. Our failure to act with respect to a breach by you or others does not waive our right to act with respect to subsequent or similar breaches. We do not guarantee we will take action against all breaches of this Agreement.</div>
<br>
<div>We may amend this Agreement at any time by posting the amended terms on this site. Except as stated elsewhere, all amended terms shall automatically be effective 30 days after they are initially posted.</div>
<br>
<div>This Agreement sets forth the entire understanding and agreement between us with respect to the subject matter hereof.</div>
</td></tr>
<tr><td style="border-top: 1px solid #ccc;">&nbsp;</td></tr>
</table>